"""
YAML-Builder – Generiert vollständiges ESPHome-YAML aus Projekt + Komponenten.

Strategie:
  1. Skeleton: esphome, board, wifi, api, ota, logger (immer da)
  2. Bus-Blöcke: i2c, spi, uart werden auto-injected wenn nötig
  3. Komponenten-Blöcke: sensor, binary_sensor, display, light, switch, etc.
  4. Custom-Components: external_components + raw YAML snippets
"""
from __future__ import annotations

import logging
from collections import defaultdict
from typing import Optional

from .schema import ForgeProject, ProjectComponent

log = logging.getLogger(__name__)

# ── Bus-Defaults per Chip-Familie ──────────────────────────────────────────────

I2C_DEFAULTS: dict[str, dict[str, int]] = {
    "ESP32":    {"sda": 21, "scl": 22},
    "ESP32-S2": {"sda": 8,  "scl": 9},
    "ESP32-S3": {"sda": 8,  "scl": 9},
    "ESP32-C3": {"sda": 8,  "scl": 9},
    "ESP32-C6": {"sda": 6,  "scl": 7},
    "ESP8266":  {"sda": 4,  "scl": 5},
}

SPI_DEFAULTS: dict[str, dict[str, int]] = {
    "ESP32":    {"clk": 18, "mosi": 23, "miso": 19},
    "ESP32-S3": {"clk": 12, "mosi": 11, "miso": 13},
    "ESP32-C3": {"clk": 6,  "mosi": 7,  "miso": 5},
}

# ── Welche Komponenten auf welchen Bus-Typ angewiesen sind ─────────────────

# Mapping: component_id → bus_type (Enrichment-basiert, Fallback für Schema)
BUS_COMPONENTS: dict[str, str] = {
    # I2C
    "bme280":     "i2c", "bme680":    "i2c", "bmp280":    "i2c",
    "sht3xd":     "i2c", "sht4x":     "i2c", "aht10":     "i2c",
    "bh1750":     "i2c", "tsl2561":   "i2c", "ccs811":    "i2c",
    "sgp4x":      "i2c", "hx711":     "i2c", "ade7953":   "i2c",
    "ssd1306_i2c":"i2c", "pcf8574":   "i2c", "mcp23017":  "i2c",
    "ds1307":     "i2c", "gt911":     "i2c", "cst816":    "i2c",
    "ft5x06":     "i2c",
    # SPI
    "ili9xxx":      "spi", "ssd1306_spi": "spi", "st7789v": "spi",
    # UART
    "ld2410":     "uart", "ld2412":    "uart", "nextion": "uart",
    "pmsx003":    "uart",
    # 1-Wire
    "dallas_temp":"1wire",
    # I2S
    "i2s_audio":          "i2s",
    "i2s_audio_speaker":  "i2s",
    "i2s_audio_microphone":"i2s",
}

# Platform-Typ → YAML top-level key
PLATFORM_YAML_KEY: dict[str, str] = {
    "sensor":         "sensor",
    "binary_sensor":  "binary_sensor",
    "text_sensor":    "text_sensor",
    "switch":         "switch",
    "light":          "light",
    "output":         "output",
    "display":        "display",
    "climate":        "climate",
    "cover":          "cover",
    "fan":            "fan",
    "button":         "button",
    "number":         "number",
    "select":         "select",
    "lock":           "lock",
    "media_player":   "media_player",
    "speaker":        "speaker",
    "microphone":     "microphone",
    "touchscreen":    "touchscreen",
    "text":           "text",
}


def build_yaml(
    project: ForgeProject,
    components: list[ProjectComponent],
    enrichment: dict | None = None,
    custom_components: dict | None = None,
) -> str:
    """Generiert vollständiges ESPHome YAML für ein Projekt.

    Args:
        project: Das Forge-Projekt mit Board-Infos.
        components: Liste der hinzugefügten Komponenten mit Pin-Zuweisungen.
        enrichment: Enrichment-Daten für Platform-Typ-Lookup.
        custom_components: Custom-Component-Daten (yaml_snippet, external_source).

    Returns:
        Vollständiger YAML-String.
    """
    enrichment = enrichment or {}
    custom_components = custom_components or {}
    lines: list[str] = []

    # ── 1. Header ──────────────────────────────────────────────────────────
    lines.append("# Generated by ESPHome Forge")
    lines.append("# forge_managed: true")
    lines.append("")

    # ── 2. ESPHome Core ────────────────────────────────────────────────────
    lines.append("esphome:")
    lines.append(f"  name: {project.id}")
    lines.append(f'  friendly_name: "{project.name}"')
    lines.append("")

    # ── 3. Board / Chip ────────────────────────────────────────────────────
    platform_key = "esp8266" if "8266" in project.chip_family else "esp32"
    lines.append(f"{platform_key}:")
    lines.append(f"  board: {project.esphome_board}")
    lines.append("")

    # ── 4. WiFi ────────────────────────────────────────────────────────────
    lines.append("wifi:")
    lines.append("  ssid: !secret wifi_ssid")
    lines.append("  password: !secret wifi_password")
    lines.append("  ap:")
    lines.append(f'    ssid: "{project.name} Fallback"')
    lines.append('    password: "forge12345"')
    lines.append("")
    lines.append("captive_portal:")
    lines.append("")

    # ── 5. Standard-Dienste ────────────────────────────────────────────────
    lines.append("logger:")
    lines.append("")

    # API-Encryption mit persistiertem Key
    api_key = project.device.api_key if project.device and project.device.api_key else ""
    lines.append("api:")
    if api_key:
        lines.append("  encryption:")
        lines.append(f'    key: "{api_key}"')
    else:
        lines.append("  encryption:")
        lines.append('    key: ""')
    lines.append("")

    # OTA mit persistiertem Passwort
    ota_password = project.device.ota_password if project.device and project.device.ota_password else ""
    lines.append("ota:")
    lines.append("  platform: esphome")
    if ota_password:
        lines.append(f'  password: "{ota_password}"')

    if not components:
        return "\n".join(lines) + "\n"

    lines.append("")

    # ── 6. Bus-Blöcke ermitteln und injizieren ─────────────────────────────
    needed_buses = _detect_needed_buses(components, enrichment)
    bus_lines = _build_bus_blocks(needed_buses, components, project.chip_family)
    if bus_lines:
        lines.append("# ── Bus-Konfiguration ──")
        lines.extend(bus_lines)

    # ── 7. External Components (für custom_components) ─────────────────────
    ext_sources = _collect_external_sources(components, custom_components)
    if ext_sources:
        lines.append("# ── Externe Komponenten ──")
        lines.append("external_components:")
        for src in ext_sources:
            lines.append(f"  - source: {src}")
        lines.append("")

    # ── 8. Komponenten-Blöcke ──────────────────────────────────────────────
    # Gruppiere nach Platform-Typ (sensor, binary_sensor, display, etc.)
    platform_groups: dict[str, list[tuple[ProjectComponent, dict]]] = defaultdict(list)
    standalone: list[tuple[ProjectComponent, dict]] = []
    custom_snippets: list[str] = []

    for comp in components:
        enr = enrichment.get(comp.comp_type, {})
        cc = custom_components.get(comp.comp_type)

        # Custom-Component mit YAML-Snippet
        if cc and cc.get("yaml_snippet"):
            custom_snippets.append(cc["yaml_snippet"])
            continue

        platform_type = enr.get("platform_type")
        if platform_type and platform_type in PLATFORM_YAML_KEY:
            platform_groups[platform_type].append((comp, enr))
        else:
            standalone.append((comp, enr))

    # Platform-basierte Komponenten (sensor:, display:, etc.)
    for platform_type, group in sorted(platform_groups.items()):
        yaml_key = PLATFORM_YAML_KEY[platform_type]
        lines.append(f"# --- {yaml_key} ---")
        lines.append(f"{yaml_key}:")
        for comp, enr in group:
            comp_lines = _build_component_block(comp, enr, platform_type, indent=2)
            lines.extend(comp_lines)
        lines.append("")

    # Standalone-Komponenten (gpio, ledc, etc.)
    for comp, enr in standalone:
        comp_lines = _build_standalone_block(comp, enr)
        lines.extend(comp_lines)

    # Custom YAML-Snippets (raw einfügen)
    for snippet in custom_snippets:
        lines.append("# --- Custom Component ---")
        lines.append(snippet.rstrip())
        lines.append("")

    return "\n".join(lines) + "\n"


# ── Helfer ─────────────────────────────────────────────────────────────────────

def _detect_needed_buses(
    components: list[ProjectComponent],
    enrichment: dict,
) -> set[str]:
    """Ermittelt welche Bus-Typen von den Komponenten benötigt werden."""
    buses: set[str] = set()
    for comp in components:
        # Aus Enrichment
        enr = enrichment.get(comp.comp_type, {})
        bus = enr.get("bus_type")
        if bus and bus not in ("none", "gpio", "wifi", "ble"):
            buses.add(bus)
        # Fallback aus BUS_COMPONENTS
        elif comp.comp_type in BUS_COMPONENTS:
            b = BUS_COMPONENTS[comp.comp_type]
            if b not in ("none", "gpio", "wifi", "ble"):
                buses.add(b)
    return buses


def _build_bus_blocks(
    needed_buses: set[str],
    components: list[ProjectComponent],
    chip_family: str,
) -> list[str]:
    """Generiert die benötigten Bus-Konfigurationsblöcke."""
    lines: list[str] = []

    if "i2c" in needed_buses:
        defaults = I2C_DEFAULTS.get(chip_family, I2C_DEFAULTS["ESP32"])
        # Prüfe ob ein Komponent explizite I2C-Pins hat
        sda, scl = defaults["sda"], defaults["scl"]
        for comp in components:
            if comp.pins.get("sda"):
                sda = comp.pins["sda"]
            if comp.pins.get("scl"):
                scl = comp.pins["scl"]
        lines.append("i2c:")
        lines.append(f"  sda: GPIO{sda}")
        lines.append(f"  scl: GPIO{scl}")
        lines.append("  scan: true")
        lines.append("")

    if "spi" in needed_buses:
        defaults = SPI_DEFAULTS.get(chip_family, SPI_DEFAULTS["ESP32"])
        clk = defaults["clk"]
        mosi = defaults["mosi"]
        miso = defaults["miso"]
        for comp in components:
            if comp.pins.get("clk_pin"):
                clk = comp.pins["clk_pin"]
            if comp.pins.get("mosi_pin"):
                mosi = comp.pins["mosi_pin"]
            if comp.pins.get("miso_pin"):
                miso = comp.pins["miso_pin"]
        lines.append("spi:")
        lines.append(f"  clk_pin: GPIO{clk}")
        lines.append(f"  mosi_pin: GPIO{mosi}")
        lines.append(f"  miso_pin: GPIO{miso}")
        lines.append("")

    if "uart" in needed_buses:
        # UART-Konfiguration (benötigt explizite Pins)
        tx_pin: int | None = None
        rx_pin: int | None = None
        for comp in components:
            if comp.pins.get("tx_pin"):
                tx_pin = comp.pins["tx_pin"]
            if comp.pins.get("rx_pin"):
                rx_pin = comp.pins["rx_pin"]
        if tx_pin is not None or rx_pin is not None:
            lines.append("uart:")
            if tx_pin is not None:
                lines.append(f"  tx_pin: GPIO{tx_pin}")
            if rx_pin is not None:
                lines.append(f"  rx_pin: GPIO{rx_pin}")
            baud = 9600  # Default; kann per config überschrieben werden
            for comp in components:
                if comp.config.get("baud_rate"):
                    baud = int(comp.config["baud_rate"])
            lines.append(f"  baud_rate: {baud}")
            lines.append("")

    if "1wire" in needed_buses:
        # 1-Wire benötigt einen Pin
        ow_pin: int | None = None
        for comp in components:
            if comp.pins.get("pin") and comp.comp_type in ("dallas_temp",):
                ow_pin = comp.pins["pin"]
        if ow_pin is not None:
            lines.append("one_wire:")
            lines.append(f"  - platform: gpio")
            lines.append(f"    pin: GPIO{ow_pin}")
            lines.append("")

    if "i2s" in needed_buses:
        # I2S Audio Bus
        i2s_pins: dict[str, int] = {}
        for comp in components:
            if comp.comp_type in ("i2s_audio", "i2s_audio_speaker", "i2s_audio_microphone"):
                i2s_pins.update(comp.pins)
        if i2s_pins:
            lines.append("i2s_audio:")
            if "bclk_pin" in i2s_pins:
                lines.append(f"  i2s_bclk_pin: GPIO{i2s_pins['bclk_pin']}")
            if "lrclk_pin" in i2s_pins:
                lines.append(f"  i2s_lrclk_pin: GPIO{i2s_pins['lrclk_pin']}")
            lines.append("")

    return lines


def _build_component_block(
    comp: ProjectComponent,
    enr: dict,
    platform_type: str,
    indent: int = 2,
) -> list[str]:
    """Baut einen Platform-Component-Block (z.B. unter sensor:)."""
    prefix = " " * indent
    lines: list[str] = []

    lines.append(f"{prefix}- platform: {comp.comp_type}")
    # Name für HA
    lines.append(f'{prefix}  name: "{comp.name}"')

    # Pin-Zuweisungen
    for role, gpio in sorted(comp.pins.items()):
        # Bus-Pins (sda, scl, etc.) werden im Bus-Block behandelt
        if role in ("sda", "scl", "clk_pin", "mosi_pin", "miso_pin", "tx_pin", "rx_pin"):
            continue
        lines.append(f"{prefix}  {role}: GPIO{gpio}")

    # Weitere Config-Werte
    for key, val in sorted(comp.config.items()):
        if key in ("baud_rate",):  # Bus-Konfiguration
            continue
        lines.append(f"{prefix}  {key}: {_yaml_value(val)}")

    return lines


def _build_standalone_block(
    comp: ProjectComponent,
    enr: dict,
) -> list[str]:
    """Baut einen Standalone-Component-Block (top-level)."""
    lines: list[str] = []
    lines.append(f"{comp.comp_type}:")

    for role, gpio in sorted(comp.pins.items()):
        if role in ("sda", "scl", "clk_pin", "mosi_pin", "miso_pin", "tx_pin", "rx_pin"):
            continue
        lines.append(f"  {role}: GPIO{gpio}")

    for key, val in sorted(comp.config.items()):
        lines.append(f"  {key}: {_yaml_value(val)}")

    lines.append("")
    return lines


def _collect_external_sources(
    components: list[ProjectComponent],
    custom_components: dict,
) -> list[str]:
    """Sammelt external_components Quellen aus Custom-Components."""
    sources: list[str] = []
    seen: set[str] = set()
    for comp in components:
        cc = custom_components.get(comp.comp_type)
        if cc and cc.get("external_source"):
            src = cc["external_source"]
            if src not in seen:
                sources.append(src)
                seen.add(src)
    return sources


def _yaml_value(val: object) -> str:
    """Konvertiert einen Python-Wert in YAML-kompatiblen String."""
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, (int, float)):
        return str(val)
    if isinstance(val, str):
        # Strings mit Sonderzeichen in Anführungszeichen
        if any(c in val for c in ":{}[],'\"&*?|->!%@`"):
            return f'"{val}"'
        return val
    return str(val)
